### ISSUE TITLE
DATOS EMPRESA

### ISSUE THREAD

**Issue by anacid** [anacid/Oficina#14]
Añadir en los porcentajes, RET. practicada, para poder aplicar la retención de los intereses de la amortización, del préstamo, para que así contablemente lo lleve a otra cuenta para luego presentar el 123
![ScreenClip.png](https://zube.io/files/anacid/ad3fe31616157393450f4e611ac0f1be.png)

**Comment by gregorioruiz** [comment]
Emplea la retención sobre la base, que está para estos casos, cuando surge una retención no prevista.
