### ISSUE TITLE
Envío de presupuestos por internet

### ISSUE THREAD

**Issue by anacid** [anacid/Oficina#7]
Modificar para que aparezca el anagrama de Cid Multimedia el envíar los presupuestos por e-mail.

![ScreenClip.png](https://zube.io/files/anacid/3bfae2e30536e360a2e8c3947069ba32.png)

**Comment by gregorioruiz** [comment]
Funciona bien. 
Es el puñetero Gmail el que no lo muestra. Si te lo envías a tu hotmail lo verás. Yo lo veo en el móvil.

**Comment by anacid** [comment]
Perfecto, funciona bien, me he envíado el presupuesto a mi correo de hotmail y se ve perfectamente.
