### ISSUE TITLE
Duplicar presupuesto

### ISSUE THREAD

**Issue by anacid** [anacid/Oficina#8]
Al duplicar los presupuestos no nos permite poner número de presupuesto. 
![ScreenClip.png](https://zube.io/files/anacid/ecd7b176aef393e3a6c5c1c86c9f450d.png)

**Comment by gregorioruiz** [comment]
Ahora pide la clave. Si se deja vacía, crea el mismo presupuesto pero lleva la versión.
No sé si es útil, pero lo había empezado a hacer y ahora parece que ya lo he dejado funcionando.

**Comment by anacid** [comment]
lo he probado, al duplicar el presupuesto ya puedo poner la clave, y lo hace perfectamente.
Lo doy por hecho y probado.
